# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  helper:
      class: AppBundle\Utils\Helper
  security.basic_auth_request_matcher:
        class: AppBundle\Security\BasicAuthRequestMatcher
  security.logout_rest_handler:
        class: AppBundle\Security\LogoutRestHandler
  security.basic_auth_entry_point:
      class: AppBundle\Security\BasicAuthEntryPoint
  security.form_login_authenticator:
      class: AppBundle\Security\FormLoginAuthenticator
      arguments: ["@router", "@security.password_encoder"]

  app.request_listener:
      class: AppBundle\EventListener\RequestListener
      arguments: ['@logger']
      tags:
          - { name: kernel.event_listener, event: kernel.request }

  app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  app.product_listener:
        class: AppBundle\EventListener\ProductCreatedListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: product.created }
            - { name: monolog.logger, channel: product }
